<a href="https://colab.research.google.com/github/keerthana461-cell/codeAlpha-tasks/blob/Codealpha-stock-portfolios-tracker/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
arr_1d=np.array([1,2,4,5])
print(arr_1d)

[1 2 4 5]


In [6]:
arr_2d=np.array([(1,2),(3,4)])
print(arr_2d)


[[1 2]
 [3 4]]


In [16]:
arr_3d=np.zeros([2,3,4])
print(arr_3d)
print("size:",arr_3d.size)
print("shape:",arr_3d.shape)
print("dimension:",arr_3d.ndim)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
size: 24
shape: (2, 3, 4)
dimension: 3


In [17]:
#datatype
arr_int32=np.array([1,2,3],dtype=np.int32)
print("data type of arr_int4=32:",arr_int32.dtype)

data type of arr_int4=32: int32


In [19]:
arr_float32=np.array([1.2,3.3,5.6], dtype=np.float32)
print("memory",arr_float32.itemsize*arr_float32.size,"bytes")

memory 12 bytes


In [21]:
full_array=np.full((2,4),5)
print(full_array)

[[5 5 5 5]
 [5 5 5 5]]
